<!-- sitemap.xsl -->

<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9" >
	
	
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html>
      <head>
      
      <title>XML Sitemap</title>
			<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
        *{
          font-family:Verdana, Geneva, Tahoma, sans-serif;
        }
          table {
            border-collapse: collapse;
            width: 80%;
            margin:auto;
          }

          th, td {
            border: 1px solid #dddddd;
            text-align: left;
            font-size:14px;
            padding: 8px;
          }

          th {
            background-color: #f2f2f2;
          }
        </style>
      </head>
      <body>
        <h2 style="width:80%;margin:auto; ">Sitemap
        <p style="font-size:12px;font-weight:100;">Automatically generated by <strong>TikDrop</strong> </p></h2>
        
        <table>
          <tr>
            <th width="70%">Location</th>
            <th width="25%">Last Modified</th>
          </tr>
          <xsl:for-each select="//s:url">
            <tr>
              <td>
                <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
              </td>
              <td>
                <xsl:value-of select="s:lastmod"/>
              </td>
            </tr>
          </xsl:for-each>

          <xsl:for-each select="//s:sitemap">
            <tr>
              <td>
                <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
              </td>
              <td>
                <xsl:value-of select="s:lastmod"/>
              </td>
            </tr>
          </xsl:for-each>
            
        </table>
      </body>
    </html>
  </xsl:template>

</xsl:stylesheet>
